services:
  sui-node:
    # Note: Update the tag to the latest version of mysten/sui-node for mainnet or testnet.
    image: mysten/sui-node:mainnet-v1.19.1
    ports:
      - "8080:8080"
      - "8084:8084/udp"
      - "9000:9000"
      - "9184:9184"
    volumes:
      - ./fullnode-template.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./suidb:/opt/sui/db:rw
      # Make sure the checkpoints directory is explicitly mounted to the shared volume
      # - sui_checkpoints:/checkpoints:rw
      # Add this line to mount the checkpoints directory
      # - ./checkpoints_indexer:/checkpoints_indexer:rw
    command: ["/opt/sui/bin/sui-node", "--config-path", "/opt/sui/config/fullnode.yaml"]

